name: PMD

on:
  push:
  pull_request:

jobs:
  pmd-analysis:
    name: Run PMD Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git Repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Download and Extract PMD 7.0.0-rc4
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc4/pmd-dist-7.0.0-rc4-bin.zip
          unzip pmd-dist-7.0.0-rc4-bin.zip
          echo "PMD_HOME=$(pwd)/pmd-bin-7.0.0-rc4" >> $GITHUB_ENV
          echo "$(pwd)/pmd-bin-7.0.0-rc4/bin" >> $GITHUB_PATH

      - name: Run PMD Analysis
        run: |
          $PMD_HOME/bin/run.sh pmd -d src/main/java -R rulesets/java/quickstart.xml -f sarif -r pmd-report.sarif

      - name: Upload PMD Report to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
